git commit

diff --git a/.github/actions/terraform/action.yml b/.github/actions/terraform/action.yml
--- a/.github/actions/terraform/action.yml
+++ b/.github/actions/terraform/action.yml
@@ -28,20 +28,13 @@ runs:
       shell: bash
       working-directory: ${{ inputs.environment }}/vault
       continue-on-error: true
-
-    #TODO: this step isn't running
     - uses: actions/github-script@v6
-      if: ${{ github.event_name == 'pull_request' }}
+      if: github.event_name == 'pull_request'
       env:
         PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
       with:
+        github-token: ${{ secrets.GITHUB_TOKEN }}
         script: |
-          const run_url = process.env.GITHUB_SERVER_URL + '/' + process.env.GITHUB_REPOSITORY + '/actions/runs/' + process.env.GITHUB_RUN_ID
-          const run_link = '<a href="' + run_url + '">Actions</a>.'
-          const fs = require('fs')
-          const plan_file = fs.readFileSync('plan.out', 'utf8')
-          const plan = plan_file.length > 65000 ? plan_file.toString().substring(0, 65000) + " ..." : plan_file
-          const truncated_message = plan_file.length > 65000 ? "Output is too long and was truncated. You can read full Plan in " + run_link + "<br /><br />" : ""
           const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
           #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
           #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
@@ -54,38 +47,80 @@ runs:
           </details>
 
           #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-          
-          <details><summary>Show Plan</summary>
-          
-          \`\`\`\n
-          ${plan}
-          \`\`\`
-          
-          </details>
-          ${truncated_message}
 
-          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ github.workspace }}\`, Workflow: \`${{ github.workflow }}\`*`;
-            
+          <details><summary>Show Plan</summary>
+
+          \`\`\`\n
+          ${process.env.PLAN}
+          \`\`\`
+
+          </details>
+
+          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
+
           github.rest.issues.createComment({
             issue_number: context.issue.number,
             owner: context.repo.owner,
             repo: context.repo.repo,
             body: output
           })
-    - name: Terraform Plan Status
-      if: steps.plan.outcome == 'failure'
-      run: exit 1
-      shell: bash
-          
-    # - name: approve
-    #   if: ${{ github.event.inputs.approver_required == 'true' }}
-    #   uses: actions/request-approval@v2
+    # #TODO: this step isn't running
+    # - uses: actions/github-script@v6
+    #   if: ${{ github.event_name == 'pull_request' }}
+    #   env:
+    #     PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
     #   with:
-    #     reviewers: octocat #TODO: change to some other approver
+    #     script: |
+    #       const run_url = process.env.GITHUB_SERVER_URL + '/' + process.env.GITHUB_REPOSITORY + '/actions/runs/' + process.env.GITHUB_RUN_ID
+    #       const run_link = '<a href="' + run_url + '">Actions</a>.'
+    #       const fs = require('fs')
+    #       const plan_file = fs.readFileSync('plan.out', 'utf8')
+    #       const plan = plan_file.length > 65000 ? plan_file.toString().substring(0, 65000) + " ..." : plan_file
+    #       const truncated_message = plan_file.length > 65000 ? "Output is too long and was truncated. You can read full Plan in " + run_link + "<br /><br />" : ""
+    #       const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+    #       #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+    #       #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+    #       <details><summary>Validation Output</summary>
+
+    #       \`\`\`\n
+    #       ${{ steps.validate.outputs.stdout }}
+    #       \`\`\`
+
+    #       </details>
+
+    #       #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+          
+    #       <details><summary>Show Plan</summary>
+          
+    #       \`\`\`\n
+    #       ${plan}
+    #       \`\`\`
+          
+    #       </details>
+    #       ${truncated_message}
+
+    #       *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ github.workspace }}\`, Workflow: \`${{ github.workflow }}\`*`;
+            
+    #       github.rest.issues.createComment({
+    #         issue_number: context.issue.number,
+    #         owner: context.repo.owner,
+    #         repo: context.repo.repo,
+    #         body: output
+    #       })
+    # - name: Terraform Plan Status
+    #   if: steps.plan.outcome == 'failure'
+    #   run: exit 1
+    #   shell: bash
+          
+    # # - name: approve
+    # #   if: ${{ github.event.inputs.approver_required == 'true' }}
+    # #   uses: actions/request-approval@v2
+    # #   with:
+    # #     reviewers: octocat #TODO: change to some other approver
     
-    - name: Terraform Apply
-      # only on main branch
-      if: ${{ github.ref == 'refs/heads/main' }}
-      run: terraform apply -no-color terraform.plan
-      shell: bash
-      working-directory: ${{ inputs.environment }}/vault
+    # - name: Terraform Apply
+    #   # only on main branch
+    #   if: ${{ github.ref == 'refs/heads/main' }}
+    #   run: terraform apply -no-color terraform.plan
+    #   shell: bash
+    #   working-directory: ${{ inputs.environment }}/vault
